### ISSUE TITLE
The sigstore command on `add_to_pythondotorg.py` still asks for interactive input.

### ISSUE THREAD

**Issue by pablogsal** [python/release-tools#25]
Unfortunately, the release script is still broken because the sigstore command on the server still blocks. Login into the machine shows that it still asks for the token in stdin.

**Comment by pablogsal** [comment]
CC: @di

**Comment by pablogsal** [comment]
See also: https://github.com/python/release-tools/pull/26

**Comment by di** [comment]
ACK, I know what it is, fixing this now.
