### ISSUE TITLE
Date and Release fields should be removed from prev_branch's whatsnew when creating new_branch's whatsnew

### ISSUE THREAD

**Issue by zware** [python/release-tools#34]
Somewhere around https://github.com/python/release-tools/blob/a8894a378b250a7dc16b8fb88b5a88865e56bc33/run_release.py#L865-L870

we can automatically remove the `:Release:` and `:Date:` fields from the previous branch's whatsnew to avoid issues like python/cpython#100700 and python/cpython#73905.

**Comment by oliver-rew** [comment]
Any qualms with me taking this one?

**Comment by hugovk** [comment]
Please go ahead, thank you!
